// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ju7ipQ0vAdLlfyN7NHx_gBSPKTDoh3g',
    appId: '1:603821450421:web:8bdcc26892308fe7554afc',
    messagingSenderId: '603821450421',
    projectId: 'shilpa-study-app',
    authDomain: 'shilpa-study-app.firebaseapp.com',
    storageBucket: 'shilpa-study-app.firebasestorage.app',
    measurementId: 'G-908V3F5B68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6h-769iA-nYarPZJY07TK1j34t44asYU',
    appId: '1:603821450421:android:181806a15f041c06554afc',
    messagingSenderId: '603821450421',
    projectId: 'shilpa-study-app',
    storageBucket: 'shilpa-study-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlz04lxW3URvaTnFdUb1GJzl1v0n-JrYg',
    appId: '1:603821450421:ios:fcf2379a161dc3f6554afc',
    messagingSenderId: '603821450421',
    projectId: 'shilpa-study-app',
    storageBucket: 'shilpa-study-app.firebasestorage.app',
    androidClientId: '603821450421-befc7uvhbood5s6044dg0va8f79ntqte.apps.googleusercontent.com',
    iosClientId: '603821450421-l5pv6f8vsghc8q2h115lhp41kgflurai.apps.googleusercontent.com',
    iosBundleId: 'com.example.shilpaStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlz04lxW3URvaTnFdUb1GJzl1v0n-JrYg',
    appId: '1:603821450421:ios:fcf2379a161dc3f6554afc',
    messagingSenderId: '603821450421',
    projectId: 'shilpa-study-app',
    storageBucket: 'shilpa-study-app.firebasestorage.app',
    androidClientId: '603821450421-befc7uvhbood5s6044dg0va8f79ntqte.apps.googleusercontent.com',
    iosClientId: '603821450421-l5pv6f8vsghc8q2h115lhp41kgflurai.apps.googleusercontent.com',
    iosBundleId: 'com.example.shilpaStudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ju7ipQ0vAdLlfyN7NHx_gBSPKTDoh3g',
    appId: '1:603821450421:web:4abb51f94b055aee554afc',
    messagingSenderId: '603821450421',
    projectId: 'shilpa-study-app',
    authDomain: 'shilpa-study-app.firebaseapp.com',
    storageBucket: 'shilpa-study-app.firebasestorage.app',
    measurementId: 'G-HNESW5SRN4',
  );
}
